name: Timelist
version: 1.0.0
description: A timed whitelist alternative.
author: austinv11
website: austinv11.github.io
 
main: io.github.austinv11.Timelist.Timelist
commands:
   timelist:
      description: The command representing all timelist commands.
      usage: /<command> help
      permission: Timelist.timelist
      permission-message: You don't have permission

permissions:
   Timelist.*:
        description: Gives access to all Timelist permissions.
   Timelist.timelist:
        description: The command representing all timelist commands.