name: Timelist
version: 1.0.0-b2
description: A timed whitelist alternative.
author: austinv11
website: austinv11.github.io
 
main: io.github.austinv11.Timelist.Timelist
commands:
   timelist:
      description: The command representing all timelist commands.
      usage: /<command> help
      permission: Timelist.timelist
      permission-message: You don't have permission

permissions:
   Timelist.*:
        description: Gives access to all Timelist permissions.
   Timelist.timelist:
        description: The command representing all timelist commands.
        default: true
   Timelist.timelistHelp:
        description: The command representing the /timelist help command.
        default: true
   Timelist.timelistList:
        description: The command representing the /timelist list command.
   Timelist.timelistAdd:
        description: The command representing the /timelist add command.
   Timelist.timelistRemove:
        description: The command representing the /timelist remove command.
   Timelist.timelistSet:
        description: The command representing the /timelist set command.
   Timelist.timelistTime:
        description: The command representing the /timelist time command.
        default: true